// <auto-generated/>
// This file auto generated by the Wintellect TFS Build Number Targets.
// See https://github.com/Wintellect/WintellectTFSBuildNumber for more information.
[assembly:System.Reflection.AssemblyTitle("Developer Build_2014010062001_17837RWA-308")]
[assembly:System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly:System.Reflection.AssemblyFileVersion("1.0.14006.2001")]
[assembly:System.Reflection.AssemblyInformationalVersion("1.0.14006-alpha2001")]
