// <auto-generated/>
// This file auto-generated by the Wintellect TFS Build Number Targets.
// See https://github.com/Wintellect/WintellectTFSBuildNumber for more information.
module AssemblyVersionInfo
[<assembly:System.Reflection.AssemblyTitle("Developer Build_201401031307_17837RWA-308")>]
[<assembly:System.Reflection.AssemblyVersion("1.0.0.0")>]
[<assembly:System.Reflection.AssemblyFileVersion("1.0.14003.1307")>]
[<assembly:System.Reflection.AssemblyInformationalVersion("1.0.14003-alpha01031307")>]
do()
