// <auto-generated/>
// This file auto-generated by the Wintellect TFS Build Number Targets.
// See https://github.com/Wintellect/WintellectTFSBuildNumber for more information.
module AssemblyVersionInfo
[<assembly:System.Reflection.AssemblyTitle("Developer Build_2014010061734_ESX220T")>]
[<assembly:System.Reflection.AssemblyVersion("1.0.0.0")>]
[<assembly:System.Reflection.AssemblyFileVersion("1.0.14006.1734")>]
[<assembly:System.Reflection.AssemblyInformationalVersion("1.0.14006-alpha1734")>]
do()
