// <auto-generated/>
// This file auto generated by the Wintellect TFS Build Number Targets.
// See https://github.com/Wintellect/WintellectTFSBuildNumber for more information.
[assembly:System.Reflection.AssemblyTitle("Developer Build_2014010031810_17837RWA-308")]
[assembly:System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly:System.Reflection.AssemblyFileVersion("1.0.14003.1810")]
[assembly:System.Reflection.AssemblyInformationalVersion("1.0.14003-alpha1810")]
